
server:
  port: 8766

spring:
  application:
    name: Zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ribbon:
    Readtimeout: 0
    Sockettimeout: 0
  routes:
    simulation-service:
      path: /simulation/**
      serviceId: simulation
    save-service:
      path: /save/**
      serviceId: save
    statistics:
       path: /statistics/**
       serviceId: statistics